name: Run Tests

on: [push, pull_request]

defaults:
  run:
    shell: bash -l {0}

concurrency:
  # make sure only one run of this workflow for a given PR or a given branch
  # can happen at one time. previous queued or started runs will be cancelled.
  # github.workflow is the workflow name
  # github.ref is the ref that triggered the workflow run
  # on push, this is refs/heads/<branch name>
  # on pull request, this is refs/pull/<pull request number>/merge
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    # Below config copied from the setup-slurm-action docs:
    # https://github.com/koesterlab/setup-slurm-action
    #
    # For the action to work, you have to supply a mysql
    # service as defined below.
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - "8888:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    # For gcp auth, add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch complete history for accurate versioning

      - uses: koesterlab/setup-slurm-action@v1

      - name: Setup conda environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: env
          create-args: >-
            python=3.13
            natcap.invest
            pytest
          condarc: |
            channels:
              - conda-forge
              - nodefaults
          init-shell: bash

      - name: List conda environment
        run: micromamba list

      - uses: 'google-github-actions/auth@v3'
        with:
          service_account: 'invest-compute-wksp-uploader@natcap-servers.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/1098785064656/locations/global/workloadIdentityPools/github-actions-invest-compute/providers/invest-compute'

      - name: Install package
        run: cd invest_processes && pip install .

      - name: Run tests
        run: |
          export PYGEOAPI_CONFIG=invest_processes/pygeoapi-config.yml
          export PYGEOAPI_OPENAPI=invest_processes/openapi.yml
          pygeoapi openapi generate $PYGEOAPI_CONFIG --output-file $PYGEOAPI_OPENAPI
          pytest --log-cli-level=DEBUG tests/
